### Pants Index
GET http://localhost:3000/pants

### Pants Show
GET http://localhost:3000/pants/3

### Pants Post
POST http://localhost:3000/pants
Content-Type: application/json

{
  "name": "test",
  "size": "L",
  "length": 34,
  "waist": 36
}

### Pants Delete
DELETE http://localhost:3000/pants/6